* A Notification Server for Emacs

DNel is an Emacs package that implements a
[[https://people.gnome.org/~mccann/docs/notification-spec/notification-spec-latest.html][Desktop Notifications service]]
in pure Lisp, aspiring to be a small, but flexible drop-in replacement for
standalone daemons like [[https://dunst-project.org/][Dunst]].
Active notifications are tracked
whenever the global minor mode ~dnel-mode~ is active and
can be retrieved as a list with the function ~dnel-notifications~.
DNel also provides a hook ~dnel-notifications-changed-functions~, so that
users can handle newly added and removed notifications as they see fit.
To be useful out of the box, DNel records past and present notifications
in the interactive log buffer ~*dnel-log*~.

** Basic Usage

For now, simply execute the ~package-install-file~ command and
point it to a local copy of this repository.
The package will hopefully end up on [[https://melpa.org][MELPA]] in due time.

After installation, ensure that no other notification daemon is active,
execute the ~dnel-mode~ command to activate the global minor mode, and
call the ~dnel-pop-to-log-buffer~ function to see the interactive log buffer
where past and present notifications are recorded in the background.

Every notification record has text properties so that
- hovering over its summary displays the body as a tooltip,
- the left mouse button invokes the notification's default action,
- the middle mouse button shows a menu of all available actions, and
- the right mouse button closes the notification.

** Advanced Usage

You can also
retrieve currently active notifications with the function ~dnel-notifications~
whenever the (abnormal) hook ~dnel-notifications-changed-functions~ runs.
Functions in that hook are given access to the exact notification that changed.
Read on for some suggestions.

*** Show Active Notifications

To simply display all active notifications in the mode-line,
first define a function that returns active notifications as a string:
#+NAME: list
#+BEGIN_SRC emacs-lisp :tangle yes
(defun list-notifications ()
  (mapconcat #'dnel-format-notification (dnel-notifications) ""))
#+END_SRC

Alternatively, only include the newest notification per application:
#+NAME: stack
#+BEGIN_SRC emacs-lisp :tangle yes
(defun stack-notifications (&optional hide)
  (mapconcat (lambda (notification)
               (let ((app-name (dnel-notification-app-name notification)))
                 (if (member app-name hide) ""
                   (push app-name hide)
                   (dnel-format-notification notification))))
             (dnel-notifications) ""))
#+END_SRC

Use the respective function's result as part of your mode-line
every time a new notification appears, or an old one is removed:
#+BEGIN_SRC emacs-lisp
(nconc global-mode-string '((:eval (stack-notifications))))  ; or list
(add-hook 'dnel-notifications-changed-functions (lambda (&rest _)
                                                  (force-mode-line-update t)))
#+END_SRC
